[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "MrCB08", email = "56218268+MrCB08@users.noreply.github.com"},
]
dependencies = [
    "termcolor>=2.3.0",
]
requires-python = ">=3.10"
license = {text = "None"}
